<<<<<<< HEAD
package gacha;

public enum Path {
    ABUNDANCE, ERUDITION, HUNT, HARMONY, DESTRUCTION, NIHILITY, PRESERVATION, REMEMBRANCE;
}
=======
package gacha;

public enum Path {
    ABUNDANCE, ERUDITION, HUNT, HARMONY, DESTRUCTION, NIHILITY, PRESERVATION, REMEMBRANCE;
}
>>>>>>> 67c6e43da4a346ede2d80f03966a825c93951621
